name: CI

on: pull_request

env:
  BEAKER_HYPERVISOR: docker
  BUNDLE_WITHOUT: release

jobs:
  rubocop:
    runs-on: ubuntu-latest
    name: Rubocop
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: true
      - name: Rubocop
        run: bundle exec rake rubocop

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
    name: Ruby ${{ matrix.ruby }}
    steps:
      - uses: actions/checkout@v2
      - name: Install Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Verify gem builds
        run: bundle exec gem build *.gemspec
      - name: Run unit tests
        run: bundle exec rake spec
      - name: Run acceptance tests
        run: bundle exec rake acceptance
